#' Obtain Viet Nam map data
#'
#' Returns a simple-features boundary layer for the provincial-level
#' administrative units of Viet Nam. The current layer contains the 34 units
#' effective from 1 July 2025. A 63-unit layer is retained for data collected
#' under the immediately preceding geography.
#'
#' @param geography One of `"provinces"` (the 34 units effective from July
#'   2025), `"communes"` (current commune-level units),
#'   `"provinces_63"` (the pre-July 2025 units), `"districts_63"` (the
#'   pre-July 2025 district-level units), or `"communes_63"` (the pre-July 2025
#'   commune-level units). See Details for the optional lower-level layers.
#' @param include Optional character vector of names, aliases, official
#'   two-digit codes, or ISO 3166-2 codes to retain. Vietnamese names may be
#'   supplied with or without diacritics.
#' @param region Optional character vector of socio-economic region codes
#'   (`"RRD"`, `"NMM"`, `"NCC"`, `"CH"`, `"SE"`, `"MRD"`) or English region
#'   names used to retain whole regions. Units matching either `include` or
#'   `region` are kept. Available only for the provincial geographies.
#' @param province Optional character vector of provincial-level identifiers
#'   (names, aliases, or codes) used to keep only the lower-level units that
#'   fall inside those provinces. Available for `"communes"`,
#'   `"districts_63"`, and `"communes_63"`; historical layers resolve against
#'   the 63-unit geography.
#' @param crs Coordinate reference system understood by [sf::st_transform()].
#'
#' @return An `sf` object with one row per unit. Provincial layers carry
#'   `code`, `iso`, `name_vi`, `name_en`, `type`, and `geometry`; current units
#'   created by the 2025 reform have `NA` in `iso` where no code is bundled.
#'   The lower-level layers carry `code`, `name_vi`, `name_en`, `province_code`,
#'   `province_en`, and `geometry`.
#'
#' @details The bundled geometry is projected to EPSG:3405 by default. Pass a
#'   different EPSG code or an `sf` CRS object to `crs` when another projection
#'   is required. Filtering happens before transformation.
#'
#'   The current 34-unit layer is dissolved from the exact same current
#'   commune source described below, so parent and child boundaries share the
#'   same 25 July 2026 observed snapshot. Historical `"provinces_63"` geometry
#'   remains derived from geoBoundaries. All geometry is intended for
#'   statistical graphics, not surveying, navigation, or legal determinations.
#'
#'   The bundled `"communes"` layer contains the 3,321 current commune-level
#'   units in the 25 July 2026 catalogue snapshot. It carries validity,
#'   geography-vintage, source, and geometry-accuracy columns. Its boundaries
#'   are generalized to 100 metres for statistical graphics.
#'
#'   The optional `"districts_63"` (second-level) and `"communes_63"`
#'   (third-level) layers hold the district and commune units as they existed
#'   before the July 2025 reform, which abolished the district tier and merged
#'   communes. They are historical only, are not bundled by default because of
#'   their size, and are generated by `data-raw/build_adm2.R` and
#'   `data-raw/build_adm3.R`; [vn_map()] raises an informative error when the
#'   requested layer has not been built. The commune layer contains many
#'   thousands of units, so filtering with `province` (or `include`) is
#'   strongly recommended rather than drawing it nationwide.
#'
#'   This function requires the \pkg{sf} package. Name and code lookups
#'   ([province_code()], [province_info()], [province_region()]) work without
#'   it.
#'
#' @seealso [plot_vnmap()], [province_code()], [province_info()]
#'
#' @examples
#' map <- vn_map()
#' nrow(map)
#' names(map)
#'
#' north <- vn_map(include = c("Ha Noi", "Bac Ninh"))
#' nrow(north)
#'
#' delta <- vn_map(region = "MRD")
#' nrow(delta)
#'
#' historical <- vn_map("provinces_63", crs = 4326)
#' sf::st_crs(historical)$input
#'
#' \dontrun{
#' # Lower-level layers must be built first (see data-raw/build_adm3.R).
#' hanoi_communes <- vn_map("communes_63", province = "Ha Noi")
#' }
#' @export
vn_map <- function(geography = c("provinces", "communes", "provinces_63", "districts_63",
                                 "communes_63"),
                   include = NULL, region = NULL, province = NULL,
                   crs = vnmap_crs()) {
  geography <- match.arg(geography)
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("Package 'sf' is required to load map geometry. ",
         "Install it with install.packages(\"sf\").", call. = FALSE)
  }
  file <- system.file("extdata", paste0(geography, ".rds"), package = "vnmap")
  if (!nzchar(file)) {
    script <- switch(geography, districts_63 = "build_adm2.R",
                     communes_63 = "build_adm3.R", NULL)
    stop(if (!is.null(script)) {
      paste0(sub("s_63$", "", geography), "-level geometry is not bundled. ",
             "Build it with data-raw/", script, ".")
    } else {
      "Bundled map data could not be found."
    }, call. = FALSE)
  }
  map <- readRDS(file)
  if (geography %in% c("communes", "districts_63", "communes_63")) {
    if (!is.null(region)) {
      stop("`region` is not available for lower-level geography.", call. = FALSE)
    }
    if (!is.null(province)) map <- map[.filter_province(map, province,
      if (geography == "communes") "provinces" else "provinces_63"), , drop = FALSE]
    if (!is.null(include)) map <- map[.match_units(map, include), , drop = FALSE]
  } else {
    if (!is.null(province)) {
      stop("`province` is only available for lower-level geography.", call. = FALSE)
    }
    keep <- character(0)
    if (!is.null(region)) keep <- .region_filter(region, geography)
    if (!is.null(include)) keep <- c(keep, province_code(include, geography))
    if (!is.null(region) || !is.null(include)) {
      map <- map[map$code %in% keep, , drop = FALSE]
    }
  }
  sf::st_transform(map, crs)
}

# Keep only lower-level units whose parent province matches `province`. Parent
# provinces are the pre-July-2025 (63-unit) provinces recorded at build time.
.filter_province <- function(map, province, geography = "provinces_63") {
  if (!"province_code" %in% names(map)) {
    stop("This layer carries no province codes to filter on.", call. = FALSE)
  }
  codes <- province_code(province, geography)
  hit <- map$province_code %in% codes
  if (!any(hit)) stop("No units matched `province`.", call. = FALSE)
  hit
}

# Match arbitrary lower-level identifiers against a layer's own code and name
# columns, using the same normalization as province lookups. Commune names are
# not unique nationwide, so pair `include` with `province` to disambiguate.
.match_units <- function(map, include) {
  want <- .vn_key(include)
  cols <- intersect(c("code", "name_vi", "name_en"), names(map))
  hit <- Reduce(`|`, lapply(cols, function(cn) .vn_key(map[[cn]]) %in% want))
  if (!any(hit)) stop("No lower-level units matched `include`.", call. = FALSE)
  hit
}

#' Coordinate reference system used by vnmap
#'
#' EPSG:3405 is the VN-2000 / UTM zone 48N projected CRS.
#'
#' @return An `sf` CRS object.
#'
#' @details All bundled geometries are returned in this projected CRS unless a
#'   different value is supplied to the `crs` argument of [vn_map()]. Using a
#'   projected CRS keeps distances and polygon rendering stable for national
#'   statistical maps.
#'
#' @seealso [vn_map()], [sf::st_crs()]
#'
#' @examples
#' vnmap_crs()
#' @export
vnmap_crs <- function() {
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("Package 'sf' is required for coordinate reference systems. ",
         "Install it with install.packages(\"sf\").", call. = FALSE)
  }
  sf::st_crs(3405)
}
