#' Obtain Viet Nam map data
#'
#' Returns a simple-features boundary layer for the provincial-level
#' administrative units of Viet Nam. The current layer contains the 34 units
#' effective from 1 July 2025. A 63-unit layer is retained for data collected
#' under the immediately preceding geography.
#'
#' @param geography One of `"provinces"` (the 34 units effective from July
#'   2025), `"provinces_63"` (the pre-July 2025 units), or `"districts_63"`
#'   (the pre-July 2025 district-level units; see Details).
#' @param include Optional character vector of names, aliases, official
#'   two-digit codes, or ISO 3166-2 codes to retain. Vietnamese names may be
#'   supplied with or without diacritics.
#' @param region Optional character vector of socio-economic region codes
#'   (`"RRD"`, `"NMM"`, `"NCC"`, `"CH"`, `"SE"`, `"MRD"`) or English region
#'   names used to retain whole regions. Units matching either `include` or
#'   `region` are kept. Not available for `"districts_63"`.
#' @param crs Coordinate reference system understood by [sf::st_transform()].
#'
#' @return An `sf` object with one row per unit and the following columns:
#'   `code`, `iso`, `name_vi`, `name_en`, `type`, and `geometry`. Current units
#'   created by the 2025 reform have `NA` in `iso` where no code is bundled.
#'
#' @details The bundled geometry is projected to EPSG:3405 by default. Pass a
#'   different EPSG code or an `sf` CRS object to `crs` when another projection
#'   is required. Filtering happens before transformation.
#'
#'   The 34-unit layer was constructed by dissolving historical provincial
#'   boundaries according to Decision 19/2025/QD-TTg. The source geometry is
#'   generalized and intended for statistical graphics, not surveying,
#'   navigation, or legal boundary determinations.
#'
#'   The optional `"districts_63"` layer holds the second-level (district)
#'   units as they existed before the July 2025 reform, which abolished the
#'   district tier. It is historical only, is not built by default, and is
#'   generated by `data-raw/build_adm2.R`; [vn_map()] raises an informative
#'   error when the layer has not been bundled.
#'
#'   This function requires the \pkg{sf} package. Name and code lookups
#'   ([province_code()], [province_info()], [province_region()]) work without
#'   it.
#'
#' @seealso [plot_vnmap()], [province_code()], [province_info()]
#'
#' @examples
#' map <- vn_map()
#' nrow(map)
#' names(map)
#'
#' north <- vn_map(include = c("Ha Noi", "Bac Ninh"))
#' nrow(north)
#'
#' delta <- vn_map(region = "MRD")
#' nrow(delta)
#'
#' historical <- vn_map("provinces_63", crs = 4326)
#' sf::st_crs(historical)$input
#' @export
vn_map <- function(geography = c("provinces", "provinces_63", "districts_63"),
                   include = NULL, region = NULL, crs = vnmap_crs()) {
  geography <- match.arg(geography)
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("Package 'sf' is required to load map geometry. ",
         "Install it with install.packages(\"sf\").", call. = FALSE)
  }
  file <- system.file("extdata", paste0(geography, ".rds"), package = "vnmap")
  if (!nzchar(file)) {
    stop(if (geography == "districts_63") {
      paste("District-level geometry is not bundled.",
            "Build it with data-raw/build_adm2.R.")
    } else {
      "Bundled map data could not be found."
    }, call. = FALSE)
  }
  map <- readRDS(file)
  if (geography == "districts_63") {
    if (!is.null(region)) {
      stop("`region` is not available for district geography.", call. = FALSE)
    }
    if (!is.null(include)) map <- map[.match_units(map, include), , drop = FALSE]
  } else {
    keep <- character(0)
    if (!is.null(region)) keep <- .region_filter(region, geography)
    if (!is.null(include)) keep <- c(keep, province_code(include, geography))
    if (!is.null(region) || !is.null(include)) {
      map <- map[map$code %in% keep, , drop = FALSE]
    }
  }
  sf::st_transform(map, crs)
}

# Match arbitrary district identifiers against a district layer's own code and
# name columns, using the same normalization as province lookups.
.match_units <- function(map, include) {
  want <- .vn_key(include)
  cols <- intersect(c("code", "name_vi", "name_en"), names(map))
  hit <- Reduce(`|`, lapply(cols, function(cn) .vn_key(map[[cn]]) %in% want))
  if (!any(hit)) stop("No district units matched `include`.", call. = FALSE)
  hit
}

#' Coordinate reference system used by vnmap
#'
#' EPSG:3405 is the VN-2000 / UTM zone 48N projected CRS.
#'
#' @return An `sf` CRS object.
#'
#' @details All bundled geometries are returned in this projected CRS unless a
#'   different value is supplied to the `crs` argument of [vn_map()]. Using a
#'   projected CRS keeps distances and polygon rendering stable for national
#'   statistical maps.
#'
#' @seealso [vn_map()], [sf::st_crs()]
#'
#' @examples
#' vnmap_crs()
#' @export
vnmap_crs <- function() {
  if (!requireNamespace("sf", quietly = TRUE)) {
    stop("Package 'sf' is required for coordinate reference systems. ",
         "Install it with install.packages(\"sf\").", call. = FALSE)
  }
  sf::st_crs(3405)
}
